name: Deploy Frontend to EC2

on:
  push:
    branches: [ "deployment" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
        REACT_APP_BACKEND: ${{ secrets.BACKEND_URL }}
      run: |
        echo "${EC2_KEY}" > ec2-key.pem
        chmod 600 ec2-key.pem

        # Pass the environment variable explicitly during SSH
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST \
        REACT_APP_BACKEND="$REACT_APP_BACKEND" << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          nvm use 20.17.0
          cd /home/ubuntu/Portfolio/Portfolio-Frontend
  
          # Create .env file with the passed environment variable
          echo "REACT_APP_BACKEND=${REACT_APP_BACKEND}" > .env
          
          # Verify .env file contents
          cat .env
  
          git pull origin deployment
          npm install

          # Build with the environment variable
          REACT_APP_BACKEND="${REACT_APP_BACKEND}" npm run build
  
          sudo cp -r build/* /var/www/frontend

        EOF
        
        rm ec2-key.pem